server:
  port: 8080
  servlet:
    context-path: /kicks-hub

spring:
  application:
    name: "kicks-hub"
  datasource:
    url: "jdbc:mysql://localhost:3306/kicks_hub"
    username: root
    password: 171104
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

cloudinary:
  cloud_name: "dcudlkqcm"
  api_key: "734251979716821"
  api_secret: "WHzx_91QpnZwhLi0DOrxJGMJDT4"

open-api:
  title: "KicksHub API document"
  version: "v1.0.0"
  description: "KicksHub API service"
  server-url: "http://localhost:8080"
  server-name: "server test"

jwt:
  signer-key: "vXzlkcYAWyTfH8+TZ3/Uncec1eaLoljAbOOBWsZQSeInpLZxYwXAehEkDuBUV5K8"
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in second