server:
  port: 8080
  servlet:
    context-path: /kicks-hub

spring:
  application:
    name: "kicks-hub"
  datasource:
    url: "jdbc:mysql://localhost:3306/kicks_hub"
    username: root
    password: 171104
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true